apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm # Helm repository for ArgoCD charts
    chart: argo-cd # Name of the chart
    targetRevision: 7.7.7 # Specific chart version
    helm:
      valueFiles: # Optional: Custom values file
        - values.yaml
  destination:
    server: https://kubernetes.default.svc # In-cluster Kubernetes API
    namespace: argocd # Namespace for ArgoCD deployment
  syncPolicy:
    automated:
      selfHeal: true
