apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jrang188/homelab-k8s
        revision: HEAD
        directories:
          - path: "apps/*"
  template:
    metadata:
      name: "{{path.basename}}" # Name matches directory name
    spec:
      project: default
      source:
        repoURL: https://github.com/jrang188/homelab-k8s
        path: "{{path}}"
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    applicationsSync: create-only
    preserveResourcesOnDeletion: true
