apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jrang188/homelab-k8s
        revision: HEAD
        directories:
          - path: "apps/*"
  template:
    metadata:
      name: "{{path.basename}}" # Name matches directory name
    spec:
      project: default
      source:
        repoURL: https://github.com/jrang188/homelab-k8s
        path: "{{path}}"
        targetRevision: HEAD
        chart: "{{path.basename}}" # Each directory matches a Helm chart name
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
