apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Development
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          namespace: eso
          key: credential
